### ISSUE TITLE
Enumerate Transform Catalog

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#11]
As a prerequisite to #10 we need to enumerate the list of possible data transformations we want to support for ingested data for our MVP.

* What normalization methods?
* What data transformations?
* What data scaling?

It would also be helpful to talk about transformations in generic terms to decide what features of a transform should be supported for the future.

Can we identify any transformations that are out of scope?  What are the limitations of an implementation like #10?

**Comment by jbeezley** [comment]
I implemented the methods described in Lillian's [reference file](https://github.com/girder/metabulo/blob/master/reference/2019-04-02%20Functions%20for%20Transformations.R) as a baseline.  More can be added pretty easily as needed.
