### ISSUE TITLE
Speed up REST methods

### ISSUE THREAD

**Issue by jbeezley** [girder/metabulo#114]
Now that caching has been implemented we have pretty good performance on the transform/pca computation endpoints, but many of the cleanup endpoints are still fairly slow.  Particularly, things like masking a column take up to a second.  Batching these operations helps, but it would be better to get these requests in the 100 ms range so the user doesn't notice a delay.  We have gotten about as far as we can with caching, so any further improvements will have to be more invasive.  I don't think this is the highest priority right now, but as we add more complicated methods the performance will only get worse.

The primary source of slowness is the serialization of the full `csv_file` model, which contains all sorts of derived data.  One or more of the following will help depending on the specific needs of the web client:

1. Stop sending back the `csv_file` model with `PUT` requests that occur in the cleanup view.

This will make the requests `< 100ms` like the `PUT`'s on transformations, but the web client will be responsible for either making the changes to the table view manually or calling `GET /csv/:id` on demand.

2. Reduce the size of the serialized `csv_file` model.

There are certainly unnecessary parts being sent back.  Rather than going all the way to (1), we could serialize only a portion of the model that is needed by the client.  This could be customized per endpoint as necessary.

3. Denormalize header and column ids.

The way that things like column headers are fetched it involves a SQL query plus a read from the csv file.  This is a pretty slow operation that was the initial motivator for caching.  Even with the caching it is slow because we need to compute hashes all over the place.  We could speed up read operations at the cost of complicated write transactions.

4. Remove row/column tables.

Originally, I had the idea that we would want to query csv_files for specific metabolites and/or sample id's.  We would dramatically reduce the number of db queries performed by combining them all into the csv_file table at the cost of more complicated search queries.  It's probably a good trade-off, but I'm not yet sure on the performance increase we would get out of it.

@subdavis From the profiling I've done, 1 or 2 will get us the most benefit.  Let me know if you have some suggestions to reduce what is sent back from these endpoints that would be most convenient for the web client.

**Comment by subdavis** [comment]
> Stop sending back the csv_file model with PUT requests that occur in the cleanup view.

There's a lot of server logic to be duplicated for operations like primary key change, such as what to change the row/column to that used to be the primary key.   I'd rather not update the table view manually because any inconsistency between client and server could cause weird state sync problems.

Given that, I'd propose a third option where `PUT csv/id/lable/batch` returns `{ rows: [], columns: [] l}` and none of the other fields so that the request doesn't do validation but label state is confined to the server. The table view can update quickly and run validation asynchronously.

All other suggestions sound good to me!

**Comment by subdavis** [comment]
In addition to #153 (opened that as separate because I think the mechanics for the vis requests are different), Mask/Unmask requests take 4 seconds on average for me.

I don't want to jump the gun or anything, but weren't things much better when we didn't have the R OpenCpu overhead?  Would it be worth exploring porting the operations to python?  I believe @jbeezley mentioned in a meeting that he's done basically everything he can to speed things up with the current architecture.  Are we at the end of the rope for squeezing more performance out of the current server, or are there other tricks to try?

**Comment by waxlamp** [comment]
It sounds we're in serious need of some serverside profiling. I'm woefully underinformed when it comes to Python profiling tools, let alone an OpenCPU docker image bolted on as well.

**Comment by jbeezley** [comment]
> I don't want to jump the gun or anything, but weren't things much better when we didn't have the R OpenCpu overhead? Would it be worth exploring porting the operations to python? 

It might help some, but I don't the http overhead from opencpu is particularly significant here.  I'll post some real numbers in a bit, but my recollection was that computing the validation information was taking about as long as the imputation/pipeline.

I don't want to say that all options for optimization are exhausted.  We might get another 2x speed up, but not orders of magnitude better without changing the API.

**Comment by jbeezley** [comment]
Here is some data that I collected locally from current master ([22c2010](https://github.com/girder/metabulo/tree/22c2010754edf802a2975653c3c5830e2d11ebb0)).  I timed calling the `/csv/<id>` endpoint on the large csv file. This endpoint returns all relevant information on the cleanup page.  I have memcached enabled, but I cleared the cache before executing so it represents a "worst case" scenario.

The total time was 3.3 seconds.  Of that, the dominant portions of the execution are:
* 48% (1.6 seconds) to compute [table validation information](https://github.com/girder/metabulo/blob/master/metabulo/table_validation.py#L135)
* 29% (0.97 seconds) to compute the [transformed data table](https://github.com/girder/metabulo/blob/master/metabulo/models.py#L626)
* 9.8% (0.32 seconds) to compute [measurement metadata](https://github.com/girder/metabulo/blob/master/metabulo/models.py#L636)
* 5.8% (0.19 seconds) for pandas to [parse the csv file](https://github.com/girder/metabulo/blob/master/metabulo/models.py#L459)
* 5.8% (0.19 seconds) to do [imputation](https://github.com/girder/metabulo/blob/master/metabulo/imputation.py#L9) (this is currently the only code executed on opencpu)

The measurement metadata is suspicious and there is certainly fat to be trimmed from the table validation, but that doesn't change that we are looking at > 1 seconds request times for a file of this size.

I just had a conversation with @jeffbaumes about this.  We were tossing around the idea of making the validation update an explicit interaction from the user.  So, they could make multiple changes to the table layout.  These changes could either be queued on the client (keeping the same server API) or we could send them to the server for persistence (modifying the API to not send back any of the validation information, which would make them near instant).  The user would be presented with a button to "submit" the changes, which would cause the full pipeline to be recalculated.  While this occurs, a loading animation would be present.

**Comment by jeffbaumes** [comment]
@jbeezley would you consider this done?
