### ISSUE TITLE
Allow row index to stand in for key field

### ISSUE THREAD

**Issue by waxlamp** [girder/metabulo#136]
I had to add an artificial `index` column to the [wine dataset](https://gist.github.com/waxlamp/658b63e925d50a4edb5c4d59ba2c514d) in order to be able to use it within Metabulo, but with a row-index-as-key option I could have used the file as-is.

**Comment by jeffbaumes** [comment]
I'm not sure that we want to support an implied row index. For the wine data, there was no "name" or other identifying field? It seems for most all real-world use cases for metabolomics data, the samples will be tagged with an ID, which is important for tracking purposes.

Also, when we eventually integrate data, having an imputed index key could lead to mismatches between datasets.

**Comment by waxlamp** [comment]
This would be more like a one-off option to use the index of a given dataset as the key, so it wouldn't interfere with joining together multiple datasets. It's true that this won't be a problem in a metabolomics context, so forcing the devs to add an index column by hand is not a bad permanent solution to this issue.

@jeffbaumes I'll leave it to you to close the issue.

**Comment by jeffbaumes** [comment]
I don't think I have the power to close this. @jbeezley could I be added as a dev to the repo?

**Comment by jbeezley** [comment]
Done.
