### ISSUE TITLE
Batch cleanup operations

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#157]
I suppose this would involve some kind of dirty state and a button the user would need to click to flush the changes to server.

@waxlamp do I understand correctly?

**Comment by waxlamp** [comment]
That's how I'm picturing it, but the idea didn't originate with me (maybe it was @jeffbaumes). I also believe it would be worthwhile to have a deep discussion about whether we'd want this type of interaction, especially if it means that work could inadvertently be lost (and in turn, whether we'd want to support mechanisms to prevent that from happening).

**Comment by subdavis** [comment]
Discussed during 7/23 meeting:

Decided to break label change operations and table validation apart.  Change requests will be quick so the UI isn't spinning, and validation will happen automatically in the background.

**Comment by jeffbaumes** [comment]
@jbeezley is this resolved now because of #163?

**Comment by jbeezley** [comment]
Yes
