### ISSUE TITLE
Transformation performance is bad

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#17]
From my tests so far, it looks like the performance of transformations is already pretty bad.  @jbeezley was right about the overhead of running r processes.

Each transformation costs between .20 and .25 seconds.  Might either have to batch them or come up with another approach.

**Comment by jbeezley** [comment]
Are you using the existing transformations?  Because those don't even call out to R.  I'm planning on adding memoization to the transform results once we decide that this is worth pursuing at all.  That should take care most of the performance issues.

**Comment by subdavis** [comment]
I'm seeing this when I chain 5-6 `normalize` transformations for the same table.

**Comment by jbeezley** [comment]
There are almost certainly more efficient implementations of that.  I just pasted some example code when trying to figure out exactly what "normalization" meant in this context.  Also, there shouldn't be any reason to normalize more than once as far as I know.

**Comment by subdavis** [comment]
That was just the quickest test of chaining I could think of.

If it's the actual normalization taking time, then my experiment was poorly designed. I assumed there would be overhead on each transform much larger than it's runtime.

Should probably see how it does under more realistic conditions.
