### ISSUE TITLE
Metadata API

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#21]
From the meeting yesterday, it seems there is also a metadata API on each CSV (table):

Both orders (measurements and samples) will have:

* a single primary key
* a list of secondary or auxiliary keys
* other things?  We should get a list from Tomas.

We could also handle enable/disable with metadata.  It looks like the drop row/col transform has been removed, so I think this is @jbeezley's idea as well?

What should that API look like?

**Comment by jbeezley** [comment]
I'm still working on the details, but my plan is to have two more tables describing the columns and rows of the tables.  Right now, I have something like this in mind for both tables:

Describing columns:

| id | csv_file_id | name | index | type | masked |
| -- | ---- | ---- | ---- | ---- | --- |
| uuid | uuid | "ID"  | 0 | "primary key" | Null |
| uuid | uuid | "Glucose"  | 1 | "data" | False |

Describing rows:

| id | csv_file_id | name | index | type | masked |
| -- | ---- | ---- | ---- | ---- | --- |
| uuid | uuid | ""  | 0 | "header" | Null |
| uuid | uuid | "S1"  | 1 | "data" | False |

What I have in mind is that the "ingestion" phase in the UI will be targeted at filling in these tables.  Once you get to the transform and analysis phases, these should all be immutable.

**Comment by jbeezley** [comment]
As far the metadata associated with CSV file (type of data, type of sample), these will just be columns on the CSV file table (or we can stuff it in "meta").  It is just passive information provided to the user, so I don't think it matters much.

**Comment by subdavis** [comment]
> Once you get to the transform and analysis phases, these should all be immutable.

What's the need for this immutability?  Any mutation on these two tables would potentially invalidate the transformation pipeline, but that seems easy enough to re-run and handle errors on.

I can imagine locking this data in and not letting the user change it after the first pass could be quite frustrating.  I'm thinking of this interface more as something you can revisit to enable/disable stuff, change your imputation method, etc and have graphs update as you do it.

----------------

On a completely different note, would it make sense to force data into a "samples are in columns" mindset?  I think it would make writing both the frontend and backend easier.

We could use some trivial detection and transform it as soon as the data is ingested, before they even see the cleanup UI.

**Comment by jbeezley** [comment]
> What's the need for this immutability? Any mutation on these two tables would potentially invalidate the transformation pipeline, but that seems easy enough to re-run and handle errors on.

I just mean that the transform and analysis stages can't change them.  I didn't mean to imply you can't go back to the ingest stages and modify them again.  I'm just trying to structure what kind of operations are allowed in each stage of the pipeline.

**Comment by jbeezley** [comment]
> On a completely different note, would it make sense to force data into a "samples are in columns" mindset? I think it would make writing both the frontend and backend easier.

I don't understand "samples are in columns".  Could you explain?

**Comment by subdavis** [comment]
> I don't understand "samples are in columns". 

Sorry, subjects are in rows and measurements are in columns.  So that we don't have to deal with all the mirror conditions.  We have to know whether subjects are in rows or columns anyway, so we might as well store the data consistently and not have if conditions everywhere else in the code.

**Comment by subdavis** [comment]
# Re: table schema

This schema confuses me a little because there's a lot of derived state.  If I tag a row as primary key, for example, that would cause N changes for all N columns in the column table, right?  

Or if I disable (mask) a column that contains a primary and 3 secondary keys, 4 changes are needed to set mask on all of them.  if there was a primary and secondary key in both orders, you'd have 2N + 2M total things to keep up with and track.

If `name` were removed from the schema and `type`'s meaning was interpreted to be "the type of the thing at index i on the other axis", you would have NxM regardless of how many things were primary/secondary/enabled/disabled.

**Comment by jeffbaumes** [comment]
@jbeezley's schema looks pretty close to correct to me.

I am not following the logic of causing multiple updates @subdavis. Row inclusion/exclusion should be strictly independent of the column settings, so should not require multiple updates. Jon's schema looks pretty normalized to me (i.e. no repeated or dependent information).

@jbeezley what's your current plan for storing the actual tabular data matrix? I'm thinking CSV blobs would probably be ok for now.

**Comment by jeffbaumes** [comment]
@subdavis I think I follow at least one example now where M or N updates are required. If you change the primary key column, you need to change the "name" field of all the rows. Same for the setting "header" row, you will need to change all the names of the columns. But that seems reasonable to me. Having the row/column names in the DB will be very handy e.g. for populating drop-down color-by menus.

**Comment by subdavis** [comment]
I worked through an example because I was having trouble keeping it in my head:

| ID | Glucose | acetate |
|----|------------|-----------|
|  **HMDB**  | x1 | x2  |
| foo | .5 | .2 |
| bar | .3 | .03 |

columns;

| id | csv_file_id | name | index | type | masked |
| -- | ---- | ---- | ---- | ---- | --- |
| uuid | uuid | "ID"  | 0 | "primary key" | Null |
| uuid | uuid | "Glucose"  | 1 | "data" | False |
| uuid | uuid | "Acetate"  | 2 | "data" | False |
| uuid | uuid | "HMDB"  | 0 | "secondary key" | Null |
| uuid | uuid | "x1"  | 1 | ? | ? |
| uuid | uuid | "x2"  | 2 | ? | ? |

rows;

| id | csv_file_id | name | index | type | masked |
| -- | ---- | ---- | ---- | ---- | --- |
| uuid | uuid | ?  | 0 | "header" / "primary key" | Null |
| uuid | uuid | "HMDB"  | 1 | "secondary key" | Null |
| uuid | uuid | "foo"  | 1 | "data" | False |
| uuid | uuid | "bar"  | 1 | "data" | False |

There's a lot of this I guessed at, so there may be some misunderstanding, but I _think_:

* the `type=data` information is redundant since a cell is data iff it's in a row or colum marked data and not a secondary key.
* I'm not sure why `ID` was picked to describe the primary key in columns.  That string could describe the row or the column.
* I'm not sure what goes in the places where there's a `?`
* What does "header" mean, since both rows and columns have primary and secondary keys?  In the original example, how would a query determine that the row containing metabolite names is a primary key row?
* I think coloring is by secondary keys.  But I agree, all keys need to be in the database somehow.

**Comment by jeffbaumes** [comment]
My take on your example:

columns:

id|csv_file_id|name|index|type|masked
-|-|-|-|-|-
uuid|uuid|"ID"|0|"primary"|Null
uuid|uuid|"Glucose"|1|"data"|False
uuid|uuid|"Acetate"|2|"data"|False

rows:

id|csv_file_id|name|index|type|masked
-|-|-|-|-|-
uuid|uuid|"ID"|0|"primary"|Null
uuid|uuid|"HMDB"|1|"secondary"|Null
uuid|uuid|"foo"|2|"data"|False
uuid|uuid|"bar"|3|"data"|False

If we want to track multiple IDs (primary or secondary/group/etc.) per row or column in the database, things would need to be extended. But as is, I think the combination (csv_file_id, index) should be unique for each record in the row or column SQL table (could even be made the composite SQL primary key instead of the "id" uuid?).

I'm currently thinking values in non-primary-key rows and columns would remain in the CSV, not in the database tables. It could be useful to be able to query the possible values of categorical arrays (e.g. the names of the main group identifiers to populate a drop-down menu). But I think this "possible values for a column" metadata would be organized distinctly from what @jbeezley is proposing here.

**Comment by jbeezley** [comment]
> Sorry, subjects are in rows and measurements are in columns. So that we don't have to deal with all the mirror conditions. We have to know whether subjects are in rows or columns anyway, so we might as well store the data consistently and not have if conditions everywhere else in the code.

Yes, that is the plan.  One thing to keep in mind is that all subjects (or samples) are rows, but not all rows are subjects.  Some rows contain headers or some other information.  The same goes for columns.  This is largely the purpose of these tables.

Re: Re: table schema

As I was starting to respond, you posted more.  I think you are misunderstanding the intent, but I'll have to look through your examples to figure out how.

As @jeffbaumes pointed out, there will be a cascading update to the row names when the column containing the primary key changes.  I believe that is the only form of derived state.

**Comment by jbeezley** [comment]
> @jbeezley what's your current plan for storing the actual tabular data matrix? I'm thinking CSV blobs would probably be ok for now.

Yes, CSV blobs is still the plan.

> My take on your example: ...

Yes, that's what I had in mind.  There are a number of constraints I'll put in the schema, such as
* `(csv_file_id, name)` is unique
* `(csv_file_id, index)` is unique
* `masked = NULL` iff `type <> data`

**Comment by jbeezley** [comment]
> But as is, I think the combination (csv_file_id, index) should be unique for each record in the row or column SQL table (could even be made the composite SQL primary key instead of the "id" uuid?).

Yes, that is possible.  I don't have much experience with composite keys, but I can give it a try.

**Comment by subdavis** [comment]
> I think you are misunderstanding the intent,

I believe so too.  I think I can ask more productive questions once there's an implementation.  Thanks for answering my questions so far.

**Comment by subdavis** [comment]
Solved in #25, #26, #27
