### ISSUE TITLE
Which layout is better

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#50]
Personally I find them both a little ugly, but the second is better.  

One or the other will likely be necessary due to long file names.

A third option is to get rid of the page gutters, use a fluid container, and put the upload box and file list in the same row.

![Screenshot_20190320_144813](https://user-images.githubusercontent.com/4214172/54712654-38c6c500-4b23-11e9-97eb-ddd57be5599e.png)
![Screenshot_20190320_151400](https://user-images.githubusercontent.com/4214172/54712655-38c6c500-4b23-11e9-8cf7-bfefc82f36a0.png)

**Comment by waxlamp** [comment]
I like the second one better because it feels more compact, like college-ruled notepaper.
