### ISSUE TITLE
Misc. Issues with data validation

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#90]
This is just for me to keep a running log of issues I run into.  Sorry in advance if they are known/unsupported right now.

## metabolomics.kitware.com: bad gateway

Not sure what failed here.

## Validation succeeds, PCA fails.

When column data is missing (any single cell in the numeric data section), validation will pass but PCA will throw:

```text
ValueError: Expected 2D array, got scalar array instead: array=nan. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

## KeyError: 'data_variance'

The absence of a primary key (header or key) results in this 500 rather than a validation error.

## data: "Contains NaN's"

If a row is missing the key or group cell (empty cell, not empty string), the title of the error is "Invalid Group" which makes sense, but the data says "Contains NaN's" which doesn't make sense because the expected value for key/group is a string, not a number.

**Comment by jbeezley** [comment]
> bad gateway

What is the context of this?  The page just failed to load?  I'll try to search the logs.

> Validation succeeds, PCA fails

This shouldn't technically be happening now, but I'm not terribly surprised it is.  It is probably the imputation failing for some reason.

> KeyError: 'data_variance'

Probably an edge case I missed.  I didn't add too much testing in the first pass.

> data: "Contains NaN's"

Yeah, that seems wrong.  I'll change the message.

**Comment by subdavis** [comment]
> What is the context of this? The page just failed to load? I'll try to search the logs.

No context, it happens for any file I try to upload at the moment.  

> It is probably the imputation failing for some reason.

Once the deployed version is fixed I can check to make sure this isn't an issue with my local environment.  Same for those other cases.  Then I can paste links to reproduce.

**Comment by jbeezley** [comment]
Ahh, maybe time to consider sentry.

**Comment by jbeezley** [comment]
The bad gateway error seems to be resolved for now.

**Comment by jbeezley** [comment]
The issues here should be addressed now.  If PCA fails when validation succeeds, #99 should help narrow down the problem.
