### ISSUE TITLE
Batch Modify Row/Column

### ISSUE THREAD

**Issue by subdavis** [girder/metabulo#91]
It would be nice to have an endpoint 

`PUT /csv/<uuid:csv_id>/batch/label`

with body:

```jjavascript
[
  { context: 'row', index: 0, label: 'metadata' },
  { context: 'column', index: 4, label: 'key'},
]
```

I actually don't see the utility of the regular endpoints if we had this -- it would be easier to use batch for everything.  It would also be nice to not have to encode type info into the key names: `row_type` vs `type`.

I'm going to take a stab at this.

**Comment by jbeezley** [comment]
:+1:
